[project]
name = "geoloc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "folium>=0.20.0",
    "geopy>=2.4.1",
    "pyproj>=3.7.1",
    "shapely>=2.1.1",
]
